[package]
name = "tensorx-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
tensorx-core = { path = "../tensorx-core" }
pollster = "0.3"
wgpu = { version = "0.19"}
bytemuck = { version = "1.14", features = ["derive"] }
