[package]
name = "tensr-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
tensr-core = { path = "../tensr-core" }
pollster = "0.3"
wgpu = { version = "0.19"}
bytemuck = { version = "1.14", features = ["derive"] }
